language: php

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSER_ROOT_VERSION=4.x-dev

matrix:
  include:
    -
      php: 7.4
      env: 'PHPSTAN_TEST=1'
    -
      php: 7.1
      env: 'PHPUNIT_TEST=1'
    -
      php: 7.2
      env: 'PHPUNIT_COVERAGE_TEST=1'
    -
      php: 7.3
      env: 'PHPUNIT_TEST=1'
    -
      php: 7.4
      env: 'PHPUNIT_TEST=1'
    -
      php: 7.4
      env: 'INSTALLER_VERSION=4.5 DUPLICATE_CODE_CHECK=1'
    -
      php: 7.4
      env: 'INSTALLER_VERSION=4.5 LINT_CHECK=1'

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - 'if [[ $DUPLICATE_CODE_CHECK ]]; then sudo apt remove -y nodejs && curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh && sudo apt install -y build-essential nodejs && which npm && npm install jscpd@3.2.1  ;fi'
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - composer validate # --strict here?
  - 'composer global require hirak/prestissimo'
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - 'if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests '''' flush=all; fi'
  - 'if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit tests --coverage-clover=coverage.xml '''' flush=all; fi'
  - 'if [[ $DUPLICATE_CODE_CHECK ]]; then node_modules/jscpd/bin/jscpd src ; fi'
  - 'if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=ruleset.xml --extensions=php --tab-width=4 -sp src tests ; fi'
  - 'if [[ $LINT_CHECK ]]; then vendor/bin/parallel-lint src/ tests/ ; fi'
  - 'if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=8 -c tests/phpstan.neon src/ ; fi'
after_script:
  - 'if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi'
